/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Bi:fileEarmarkWordFill': typeof import('~icons/bi/file-earmark-word-fill')['default']
    Contributors: typeof import('./theme/components/Contributors.vue')['default']
    CopyRight: typeof import('./theme/components/CopyRight.vue')['default']
    'EosIcons:modifiedDate': typeof import('~icons/eos-icons/modified-date')['default']
    'Fa6Solid:copyright': typeof import('~icons/fa6-solid/copyright')['default']
    GitTalk: typeof import('./theme/components/git-talk.vue')['default']
    Link: typeof import('./theme/components/NavBox/link.vue')['default']
    Nav: typeof import('./theme/components/Nav/index.vue')['default']
    NavBox: typeof import('./theme/components/NavBox/index.vue')['default']
    'Octicon:feedPerson16': typeof import('~icons/octicon/feed-person16')['default']
    'Ooui:clock': typeof import('~icons/ooui/clock')['default']
    PageInfo: typeof import('./theme/components/PageInfo/PageInfo.vue')['default']
    'Ph:eyeFill': typeof import('~icons/ph/eye-fill')['default']
    'RadixIcons:update': typeof import('~icons/radix-icons/update')['default']
  }
}
